// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA07py9WtnzLdZiLJ1b_cwspLp3yj-FOCM',
    appId: '1:1014675824724:web:ff760ea103804f86404dc1',
    messagingSenderId: '1014675824724',
    projectId: 'sample-b2dfe',
    authDomain: 'sample-b2dfe.firebaseapp.com',
    storageBucket: 'sample-b2dfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkOKArElyFls_AL4KexbGgiCHVwDSafqk',
    appId: '1:1014675824724:android:81a241e2fbe49d0d404dc1',
    messagingSenderId: '1014675824724',
    projectId: 'sample-b2dfe',
    storageBucket: 'sample-b2dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeGIO3qMy46MAhh5zza4UXfg2WXr3MzEI',
    appId: '1:1014675824724:ios:c9137907fe253fcb404dc1',
    messagingSenderId: '1014675824724',
    projectId: 'sample-b2dfe',
    storageBucket: 'sample-b2dfe.appspot.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeGIO3qMy46MAhh5zza4UXfg2WXr3MzEI',
    appId: '1:1014675824724:ios:eeda9475bf5b1a8e404dc1',
    messagingSenderId: '1014675824724',
    projectId: 'sample-b2dfe',
    storageBucket: 'sample-b2dfe.appspot.com',
    iosBundleId: 'com.example.sample.RunnerTests',
  );
}
